version: '3.12'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"      # MinIO API 포트
      - "9001:9001"      # MinIO 콘솔 포트
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  model-registry:
    build:
      context: .             # Dockerfile 경로
    ports:
      - "5001:5001"              # model-registry API 포트
    environment:
      MINIO_ENDPOINT: minio:9000 # MinIO 엔드포인트
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - minio